[package]
name = "okapi-rewrite"
version = "0.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

[[bin]]
name = "okapi"
path = "src/main.rs"

[[bin]]
name = "okapi-helper-genoverlay"
path = "src/genoverlay.rs"

[[bin]]
name = "okapi-helper-genprofile"
path = "src/genprofile.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "2"
actix-rt = "1"
base64 = "0.12"
env_logger = "0.7"
reqwest = "0.10"
image = "0.23"
lazy_static = "1.4"
nix = { git = "https://github.com/Gelbpunkt/nix.git", branch = "master" }
usvg = "0.10"
resvg-raqote = "0.10"
rusttype = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.imageproc]
git = "https://github.com/image-rs/imageproc.git"
