[package]
name = "okapi"
version = "1.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", default_features = false }
base64 = "0.12"
conv = "0.3"
env_logger = "0.7"
image = { version = "0.23", default_features = false, features = ["gif", "jpeg", "png", "webp", "jpeg_rayon"] }
imageproc = "0.21"
lazy_static = "1.4"
resvg-raqote = { git = "https://github.com/Gelbpunkt/resvg-raqote.git", default_features = false }
reqwest = { version = "0.10", default_features = false, features = ["rustls-tls"] }
rusttype = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
textwrap = "0.12"
usvg = { version = "0.10", default_features = false }

[profile.release]
lto = true
