[package]
name = "okapi"
version = "1.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

[dependencies]
ab_glyph = "0.2"
actix-web = { version = "3", default_features = false, features = ["rustls"] }
base64 = "0.13"
conv = "0.3"
env_logger = "0.8"
image = { version = "0.23", default_features = false, features = ["gif", "jpeg", "png", "webp"] }
imageproc = { git = "https://github.com/Gelbpunkt/imageproc", default_features = false }
lazy_static = "1.4"
resvg = { version = "0.12", default_features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
textwrap = "0.12"
usvg = { version = "0.12", default_features = false }

[profile.release]
lto = "thin"
