[package]
name = "okapi-rewrite"
version = "1.0.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

[[bin]]
name = "okapi"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "3.0.0-beta.1"
base64 = "0.12"
env_logger = "0.7"
image = "0.23"
imageproc = "0.21"
lazy_static = "1.4"
resvg = "0.11"
reqwest = "0.10"
rusttype = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
textwrap = "0.12"
usvg = "0.11"
